name = "rrc-org-invite"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-04"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"